services:
  app:
    build: .
    container_name: grants-template-app
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - storage_data:/var/www/html/storage
      - cache_data:/var/www/html/bootstrap/cache
    depends_on:
      - db
    environment:
      DB_CONNECTION: pgsql
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: grants-template
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
 
  db:
    image: postgres:16.10
    container_name: grants-template-db
    restart: always
    environment:
      POSTGRES_DB: grants-template
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
 
volumes:
  pgdata:
  storage_data:
  cache_data: